version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
      # Prevent files from having a timestamp before 1980
      - find ./node_modules -mtime +10950 -exec touch {} \;
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # - npm run eslint
      # Discover and run unit tests in the 'tests' directory
      - npm test
  build:
    commands:
      # - npm run build
      # Use AWS SAM to package the application using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml --debug
artifacts:
  type: zip
  files:
    - template-export.yml
